coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        if_not_found: success
    patch:
      default:
        target: 90%
        if_not_found: success
comment:
  layout: "reach,diff,flags,files"
ignore:
  - "packages/core/src/gql/generated/**"
  - "packages/**/src/**/*.generated.ts"
  - "packages/benchmark/src/cli/run-scenario.ts"
  - "packages/benchmark/src/fixture/seed.ts"
