packages:
  - packages/*

onlyBuiltDependencies:
  - "@biomejs/biome"
  - esbuild
  - lefthook
  - nx

catalog:
  "@types/node": ^25.2.3
  typescript: ^5.9.3
  tsup: ^8.5.0
  tsx: ^4.21.0
  vitest: ^2.1.8
  "@vitest/coverage-v8": ^2.1.8
